dist: trusty
sudo: required
language: rust
cache: cargo
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
      - gcc
      - libiberty-dev
    sources:
      - kalakris-cmake

rust:
  - nightly

before_script: |
  pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH &&
  git clone https://github.com/apache/thrift.git &&
  cd thrift && git checkout -b 0.11.0 origin/0.11.0 && ./bootstrap.sh &&
  ./configure --enable-libs=no &&
  make && sudo make install && cd .. &&
  pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH &&
  cargo install cargo-travis --force && export PATH=$HOME/.cargo/bin:$PATH

script:
  - travis-cargo build
  - travis-cargo test

after_success: |
  wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
  tar xzf master.tar.gz &&
  cd kcov-master &&
  mkdir build &&
  cd build &&
  cmake .. &&
  make &&
  make install DESTDIR=../../kcov-build &&
  cd ../.. &&
  rm -rf kcov-master &&
  for file in target/debug/datafusion-*[^\.d]; do mkdir -p "target/cov/$(basename $file)"; ./kcov-build/usr/local/bin/kcov --exclude-pattern=/.cargo,/usr/lib,/.rustup --verify "target/cov/$(basename $file)" "$file"; done &&
  bash <(curl -s https://codecov.io/bash) &&
  echo "Uploaded code coverage"

env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
